@startuml

class Main {
    + {static} main(args : String[]) : void
}

class K8sClientFactory {
    + createApi() : CoreV1Api
}

interface PodMonitor {
    + onEvent(pod : V1Pod, eventType : String) : void
}

class EventWatcher {
    + EventWatcher(api : CoreV1Api, monitor : PodMonitor)
    + start() : void
}

class HealthMonitor {
    + onEvent(pod : V1Pod, eventType : String) : void
}


Main ..> K8sClientFactory : <<usa>>
Main ..> EventWatcher : <<crea>>
Main ..> HealthMonitor : <<crea>>

PodMonitor <|.. HealthMonitor

EventWatcher o--> PodMonitor : "notifica a"

@enduml